name: Build and deploy package

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: "6.0.x"
    
    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Create the package
      run: dotnet pack --configuration Release

    - name: Envio para o nuget
      run: dotnet nuget push MoneyExtension/bin/Release/*.nupkg -k oy2jv3scc6kihsdaoemaavsq6fwpqikudd7277zku4q2g4 -s https://api.nuget.org/v3/index.json